### PR TITLE
Updated logic to validate changes on configmaps, deployments and statefulsets

### LINKED ISSUE #163: Operator crashing after upgrade
Not exactly sure what's causing this yet, but creating this issue for us to track it:

```
 TASK [Create Database if no database is specified] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "error": 422, "msg": "Failed to apply object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"StatefulSet.apps \\\\\"awx-postgres\\\\\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than \\'replicas\\', \\'template\\', and \\'updateStrategy\\' are forbidden\",\"reason\":\"Invalid\",\"details\":{\"name\":\"awx-postgres\",\"group\":\"apps\",\"kind\":\"StatefulSet\",\"causes\":[{\"reason\":\"FieldValueForbidden\",\"message\":\"Forbidden: updates to statefulset spec for fields other than \\'replicas\\', \\'template\\', and \\'updateStrategy\\' are forbidden\",\"field\":\"spec\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}
```

To fix it I needed to delete and recreate my `awx` CR.

### LINKED ISSUE #215: Use HTTP Proxy
How do I configure AWX to use a HTTP proxy? With the old installation method I recall it was simply setting a couple variables in the inventory file but I'm not sure how to do it through the operator.

### PR DESCRIPTION
**Pull request by tchellomello**
Fixes: #215  
Fixes: #163

Breaking Change Warning
For instances created by `<0.0.8`, a crash will happen. Deleting the `statefulset` and `deployment` is a requirement.

Issues addressed:

* Now, whenever any changes happen on the resources used by the deployment, a new rollout will be issued
* If a `configmap` change (not custom) but the deployment is kept the same, `pod` will be deleted to load the `configmap` version
* Due to the introduction of `labels`, the `selector` field is considered `read-only`, therefore, the `deployment`  and ` statefulset` must be deleted a recreated to perform this change
* During an upgrade, when the `deployment` was rolled out, the `tower_podname`  was being assigned for the old pod in `Terminating` state which also caused the playbook to fail. Please, refer to https://github.com/ansible/awx-operator/issues/215#issuecomment-820897562 for more details 

**Some Tests**

*Note*: Instances deployed with basic `AWX`  spec
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-no-opts-from-006
```

| From Version            | Description                                   | Explanation          | Update Statefulset if required| Update Deployment  required |
| --------------------------- | -------------------------------------------- | ---------------------- | --------------------------|----------------------------|
| ` 0.0.6`                     | Deployment [:red_circle: :] Statefuletset [:red_circle:  ]         |   **crash**  `statefulset` and `deployment` must be recreated       |  No | No |
| ` 0.0.7`                     | Deployment [:red_circle:] Statefuletset [:red_circle:  ]         |   **crash**  `statefulset` and `deployment` must be recreated |   No | No |
| ` 0.0.8`                     | Deployment [:green_circle:] Statefuletset [:green_circle:  ]         | both gets updated      |  not necessary because labels already exists | Yes |
| ` devel`                     | Deployment [:green_circle:] Statefuletset [:green_circle:  ]         | both gets updated      |  not necessary because labels already exists | Yes |

### CODE REVIEW

**Review by shanemcd — APPROVED** [review]

**Comment by gamuniz** [comment]
@tchellomello Maybe we would rather document that upgrading from earlier versions might require changes to the deployments?

**Comment by tchellomello** [comment]
> @tchellomello Maybe we would rather document that upgrading from earlier versions might require changes to the deployments?

Yes, better than doing it automatically and creating a non-expected result. So let's consider if the `awx` instance is `<=0.0.7` then we point them to the docs. Let me update the PR

**Comment by tchellomello** [comment]
@gamuniz @shanemcd @Spredzy guys created the initial documentation and performed some tests trying to anticipate issues which I guess will provide a good ground now.   Thoughts and suggestions are more than welcome!

**Comment by tchellomello** [comment]
So after discussing with @shanemcd  we decided to remove the code that would handle the upgrade and enforce the `awx` kind to be recreated. That will force a new `statefulset` and  `deployment`  when the operator crashes for instances created at `<0.0.8`. 

Expected error:
```yaml
 awx-operator-5c488c8594-5c97d] TASK [installer : Create Database if no database is specified] *****************
[awx-operator-5c488c8594-5c97d] task path: /opt/ansible/roles/installer/tasks/database_configuration.yml:67 
[awx-operator-5c488c8594-5c97d] fatal: [localhost]: FAILED! => {"changed": false, "error": 422, "msg": "Failed to apply object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"StatefulSet.apps \\\\\"awx-latest-aa-007-postgres\\\\\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than \\'replicas\\', \\'template\\', and \\'updateStrategy\\' are forbidden\",\"reason\":\"Invalid\",\"details\":{\"name\":\"awx-latest-aa-007-postgres\",\"group\":\"apps\",\"kind\":\"StatefulSet\",\"causes\":[{\"reason\":\"FieldValueForbidden\",\"message\":\"Forbidden: updates to statefulset spec for fields other than \\'replicas\\', \\'template\\', and \\'updateStrategy\\' are forbidden\",\"field\":\"spec\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422} 
 awx-operator-5c488c8594-5c97d] 
 awx-operator-5c488c8594-5c97d] PLAY RECAP *********************************************************************
 awx-operator-5c488c8594-5c97d] localhost                  : ok=23   changed=1    unreachable=0    failed=1    skipped=15   rescued=0    ignored=0   

```
 To fix it:

```yaml
# kubectl delete  -f awx.yml
# kubectl apply -f awx.yml
```

**Pull request merged**
