### PR TITLE
feat: Add ingress_class_name parameter

### PR DESCRIPTION
**Pull request by aperigault**
Related to #716

Hello,
I added ingressClassName parameter compatibility in ingress template.

### CODE REVIEW

**Comment by WebSpider** [comment]
Great to see this being added :+1: 

I tried your new chart, and works fine for me on a kubespray cluster, v1.21.6

**Review by shanemcd — APPROVED** [review]

**Comment by aperigault** [comment]
Hi @shanemcd are we waiting for anything before merge ?

**Comment by WebSpider** [comment]
Well, for some reason the test to actually create the AWX cluster with this flag set failed.

**Comment by shanemcd** [comment]
I've resolved the conflict and pushed to this branch. I was going to merge it, but the last comment about the deployment failing has me concerned. Will wait for more eyes on this.

**Comment by thenets** [comment]
I tried to install and I faced the same problem. I don't have (or want to have) a default ingress, so this feature would be nice.

**Comment by aperigault** [comment]
Hi @shanemcd,
any news on this ?

**Comment by johnkoyle** [comment]
Against 0.21 the modifications to ingress.yaml.j2 are in the wrong location.  The should be a bit higher and not indented as far:

spec:
{% if ingress_class_name %}
  ingressClassName: {{ ingress_class_name }}
{% endif %}
  rules:

**Comment by atbore-phx** [comment]
Hi @shanemcd, @aperigault thanks for your works ! we are interested on this PR we use massively awx on k8s.
Let we know if you need some help on it.

**Comment by somebadcode** [comment]
@aperigault can you please address the indentation mistake that has been pointed out? The key is supposed to be directly under the spec key and not part of any of subordinate keys in the spec.

I really need this to be added ASAP or I won't be able to deploy AWX using the operator. I was about to patch this myself but I see that this has already gotten some traction and I hope that it can be merged swiftly.

This is how I would do it:
```yaml
spec:
{% if ingress_class_name %}
  ingressClassName: '{{ ingress_class_name }}'
{% endif %}
  rules:
```

**Comment by somebadcode** [comment]
Since there's no action on this one, I've opened a new one which does not contain the bad indentation. I really need this fix and I will be responding to comments in the PR I opened.

[PR #977](https://github.com/ansible/awx-operator/pull/977)

**Comment by somebadcode** [comment]
[PR #977](https://github.com/ansible/awx-operator/pull/977) has been merged and takes care of the concerns regarding the syntax.

**Comment by rooftopcellist** [comment]
These changes merged as part of https://github.com/ansible/awx-operator/pull/977/files, which also had the needed CSV parameter entries.

**Pull request closed without merging**
