### PR TITLE
Do not prepend variables name with tower_

### PR DESCRIPTION
**Pull request by Spredzy**

### CODE REVIEW

**Review by rooftopcellist — APPROVED** [review]

**Comment by rooftopcellist** [comment]
I just built this and deployed AWX with it.  The reconciliation loop is happy and the resulting AWX deployment is functional as far as I can tell.  :green_circle:

**Review by shanemcd — APPROVED** [review]

**Comment by Commifreak** [comment]
The current master README is still out-of-date:

```
  service_type: nodeport
  ingress_type: none
  hostname: awx-demo.example.com
```
for myawx. The `ingress_` has to be removed then. Otherwise a validation error will show up.

**Comment by Spredzy** [comment]
Hey @Commifreak thanks for following up on this commit.

Do you mind explaining a little bit more what's happening?

Which part of the `README.md` do you feel is inaccuurate ?
Which validation error are you seeing ? (Can you provide a stack here)? 

Thanks

**Comment by Commifreak** [comment]
The part displaying a example myawx with my posted content. Search for „ingress_“ on master Resdme.md and you will see

Gruß,
R. Kluth

**Comment by tchellomello** [comment]
@Commifreak could you be more specific, please?  

The `ingress_type` is still a valid configuration. Why do you say the `ingress_` has to be removed?  Which validation error are you seeing?

**Comment by Commifreak** [comment]
I apologize for any confusion here. I mixed something up. I was updating to 0.10.0 and had to adapt tower_ingress_type to ingress_type and thought I copied the example here. I did not and just not noticed it even after checking the master Readme.

Everything is ok. Sorry

**Pull request merged**
