### PR TITLE
Fix the custom port specification when service type is NodePort 

### LINKED ISSUE #788: Custom port for NodePort service is not working on 0.16.1
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I added the `nodeport_port` variable to the AWX manifest. But the AWX operator still assigns the random port.

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx-test
spec:
  service_type: NodePort
  nodeport_port: 8080
```
```
awx-demo-service                                  NodePort    10.104.220.226   <none>        80:31838/TCP   15m
```

I checked history on the `roles/installer/templates/service.yaml.j2` file.
https://github.com/ansible/awx-operator/commits/devel/roles/installer/templates/service.yaml.j2

It looks like the feature was added with this commit:
https://github.com/ansible/awx-operator/commit/9b072aa5490f46d6ceb437a42a49285d02cc2e17

But it was removed with the next commit:
https://github.com/ansible/awx-operator/commit/e97def44296aec7f1fd29e3e228e0671b946b34f

##### ENVIRONMENT
* AWX version: 19.5.1
* Operator version: 0.16.1
* Kubernetes version: 
* AWX install method: minikube

##### STEPS TO REPRODUCE

* Deploy AWX operator 0.16.1
* Create AWX manifest:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx-test
spec:
  service_type: NodePort
  nodeport_port: 8080
```
* Check the service port

##### EXPECTED RESULTS

I expect that the service will be listening on the specified port.

##### ACTUAL RESULTS

Service is listening on the random port.

### PR DESCRIPTION
**Pull request by ubajze**
Closes #788

### CODE REVIEW

**Review by shanemcd — APPROVED** [review]

**Comment by DomPolizzi** [comment]
Utilizing DEVEL BRANCH `NodePort_port` does not assign correctly. The Problem is not Resolved

## Kubectl deployment
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: dev-awx-env
  labels:
    app: awx
  namespace: dev-awx
spec:
  replicas: 1
  hostname: dev-awx.internal.local
  service_type: nodeport 
  nodeport_port: 30626
```
## results:
```
NAME                   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
dev-awx-env-postgres   ClusterIP   None           <none>        5432/TCP       5m38s
dev-awx-env-service    NodePort    10.233.9.146   <none>        80:30993/TCP   5m20s
```

## Changes Made:

1. Removed the environment and Operator from the Cluster
2. Cloned repo and ensured branch `devel` 
3. in `roles/installer/templates/service.yaml.j2` ensured these matched the changes in this merge
4. ran the installation
 ```
     1	#!/bin/sh
     2	export AWXOPVERSION="devel"
     3	export NAMESPACE=dev-awx
     4	rm -rf awx-operator 2> /dev/null 
     5	git clone https://github.com/ansible/awx-operator.git
     6 	cd awx-operator || exit
     7	git checkout $AWXOPVERSION
     8 	git fetch 
     9	make deploy || exit 1

```
5. ran deployment and waited for changes

**Comment by kurokobo** [comment]
@DomPolizzi 
Any changes on your local file system does not change the behavior of AWX Operator. Actual roles and templates are bundled in container image, so you have to specify `devel` tag if you want to use upstream version of Operator.

```bash
VERSION=devel make deploy
```

But regardless of your testing method, this PR does not seem to solve the problem anyway. Refer #814.

**Comment by deeco** [comment]
@kurokobo  + 1 , this does not solve the issue, Specify loadbalancer allows for the deployment to complete, for node port no service pods deploy

**Comment by deeco** [comment]
using this workaround currently with custom service. https://github.com/ansible/awx-operator/issues/291

**Pull request merged**
