### PR TITLE
Add x-descriptors for new fields

### PR DESCRIPTION
**Pull request by jessicamack**
Signed-off-by: jessicamack <jmack@redhat.com>

##### SUMMARY

Added descriptors for fields added as a part of #1182 

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by TheRealHaoLiu** [comment]
test instruction for the PR:
following instruction in https://docs.okd.io/latest/operators/operator_sdk/osdk-working-bundle-images.html

- generate bundle via `make bundle`
- verify that ./bundle directory contain bundle with the modified CSV
- generate bundle image via `make bundle-build`
- tag image to push to own quay repo `docker tag quay.io/ansible/awx-operator-bundle:v1.1.4-27-gda0a242 quay.io/haoliu/awx-operator-bundle:v1.1.4-27-gda0a242`
- pushed bundle image via `docker push quay.io/haoliu/awx-operator-bundle:v1.1.4-27-gda0a242`
- NOTE: make sure that the image repo is public to avoid having to mess with image pull secret 

validated:
- 🟢 web_replicas and task_replicas is added
image
- 🟢 validated that rest of the field does not show up since they are hidden

**Review by TheRealHaoLiu — APPROVED** [review]
LGTM

**Review by thedoubl3j — COMMENTED** [review]
lgtm will wait on @TheRealHaoLiu

**Comment by thedoubl3j** [comment]
sonofa

**Pull request merged**
