### PR TITLE
Remove usage of NAMESPACE var in README

### PR DESCRIPTION
**Pull request by sumkincpp**
##### ISSUE TYPE

- Bug, Docs Fix or other nominal change

##### SUMMARY
It was used previously, but not anymore.

### CODE REVIEW

**Comment by rooftopcellist** [comment]
Good catch.  Sure enough, if you try to pass it, minikube will now throw an error:

```
$ minikube service awx-demo-service --url -n $NAMESPACE
Error: flag needs an argument: 'n' in -n
```

Once CI is passing, we can merge this, it is running now.

**Comment by rooftopcellist** [comment]
@sumkincpp do you mind rebasing this PR and force pushing to this branch? I think that is why the molecule tests are failing atm.  The test failures are obviously unrelated to the changes you made.

**Comment by sumkincpp** [comment]
@rooftopcellist rebased to the upstream devel

**Comment by rooftopcellist** [comment]
That did the trick.  Thanks @sumkincpp !

**Pull request merged**
