### PR TITLE
Update code with capability to set the init container resources instead of using web or task container resources

### PR DESCRIPTION
**Pull request by rakesh561**
##### SUMMARY
Update code with capability to set the init container resources instead of using web or task container resources
As of now if web and task resource requirements are set for init containers.

##### ISSUE TYPE
 - New or Enhanced Feature

##### ADDITIONAL INFORMATION
Issue #971  will be addressed hopefully

### CODE REVIEW

**Comment by fosterseth** [comment]
hi, thanks for this contribution

https://github.com/ansible/awx-operator/issues/971 technically should already be solved, since we do put requests/limits on the init containers.

we will get this reviewed soon

also, regarding this pod scheduling description https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-requests-are-scheduled

pods are scheduled if the sum of the container requests are less than node capacity. Do you know if you sum includes the init container?

**Review by rooftopcellist — APPROVED** [review]

**Comment by rooftopcellist** [comment]
The PR looks good, we just need to figure out why molecule tests are failing before merge.  Could you please rebase your branch @rakesh561 ?

**Comment by rakesh561** [comment]
@rooftopcellist  i did rebase the branch.Please let me know if there is anything that needs to be done.

**Comment by rakesh561** [comment]
@rooftopcellist  i think it is now failing at Semantic Versioning

**Comment by rakesh561** [comment]
I have updated the Label to make sure semantic versioning error is resolved.If you could re-run tests/checks that would be great.

**Review by TheRealHaoLiu — APPROVED** [review]

**Pull request merged**
