### PR TITLE
update readme TOC

### PR DESCRIPTION
**Pull request by samccann**
##### SUMMARY

Cleanup the TOC and leftover sections after the move to individual files.

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by samccann** [comment]
@DesmondSanctity - can you review this PR please? It does a final cleanup of the readme file after all the rebase/merges.

**Comment by DesmondSanctity** [comment]
> @DesmondSanctity - can you review this PR please? It does a final cleanup of the readme file after all the rebase/merges.

Okay. I will do that shortly.

**Review by DesmondSanctity — APPROVED** [review]
This looks okay to me. 🚀🚀

**Comment by samccann** [comment]
@rooftopcellist - can you review as well to free up the CI for test/merging on this pr?

**Review by rooftopcellist — APPROVED** [review]

**Pull request merged**
