### PR TITLE
Use awx-manage register_default_execution_environments

### PR DESCRIPTION
**Pull request by Zokormazo**
Signed-off-by: Julen Landa Alustiza <jlanda@redhat.com>

### CODE REVIEW

**Comment by shanemcd** [comment]
We'll need to coordinate the merge of this PR and the next AWX release that includes https://github.com/ansible/awx/pull/10321, or installing the operator from devel will go 💥

**Comment by shanemcd** [comment]
Curious... how did the checks pass on this PR without pointing to an AWX image that has this command?

**Comment by Zokormazo** [comment]
> Curious... how did the checks pass on this PR without pointing to an AWX image that has this command?

k8s_exec does not fail even when the awx-manage command does not exists :D

**Review by kdelee — APPROVED** [review]

**Comment by Zokormazo** [comment]
Superseeded by #379

**Pull request closed without merging**
