### PR TITLE
tower_ee: Allow for greater flexibility when creating the ee container

### LINKED ISSUE #148: Add option to specify additional environment for EE container
Currently I can specify additional Environment for `awx-web` and `awx-task` containers using the `tower_task_extra_env` and `tower_web_extra_env` properties.
I would like to specify additional env also for the `awx-ee` container.
This is useful for example if I need to specify `https_proxy` variables.

### PR DESCRIPTION
**Pull request by Spredzy**
This commit allows one to specify extra_env and resource requirementss
for the ee container.

Fixes: https://github.com/ansible/awx-operator/issues/148

### CODE REVIEW

**Review by shanemcd — APPROVED** [review]
LGTM after tests pass.

**Comment by kimbernator** [comment]
+1 on this functionality, would be super helpful for my implementation

**Comment by JoelBChapmanII** [comment]
I'm also needing this functionality.

**Comment by rooftopcellist** [comment]
It looks like this PR just needs a rebase.

**Comment by Spredzy** [comment]
Addressed by: #406 and #407

**Pull request closed without merging**
