### PR TITLE
Docs: moved user guide segment from readme

### PR DESCRIPTION
**Pull request by LuluNwenyi**
##### SUMMARY
Moved _User Guide_ from ReadME to it's folder in /docs directory.

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### ADDITIONAL INFORMATION
This PR is in line with the docs revamp and tracked by issue [#1360](https://github.com/ansible/awx-operator/issues/1360)

### CODE REVIEW

**Comment by DesmondSanctity** [comment]
@LuluNwenyi so few things to update here:

- The table of content still has the reference to the docs moved, that part should be removed
- Create another folder inside `/docs/user-guide` directory for advanced configuration and separate the subtopics to different .md files. I think it will be more readable that way than everything in one file.
- Also, `debugging.md` and `migration.md` are already in the `docs` root folder. Just move them to `docs/user-guide/advanced-configuration` folder you will create.

I think every other thing is perfect. Thanks for the PR

**Comment by LuluNwenyi** [comment]
> @LuluNwenyi so few things to update here:
> 
> * The table of content still has the reference to the docs moved, that part should be removed
> * Create another folder inside `/docs/user-guide` directory for advanced configuration and separate the subtopics to different .md files. I think it will be more readable that way than everything in one file.
> * Also, `debugging.md` and `migration.md` are already in the `docs` root folder. Just move them to `docs/user-guide/advanced-configuration` folder you will create.
> 
> I think every other thing is perfect. Thanks for the PR

I think that we should leave the debugging and migration files in the docs root folder, for easy referencing. It's also referenced in the database config topic.

**Review by DesmondSanctity — COMMENTED** [review]
.

**Comment by DesmondSanctity** [comment]
> > @LuluNwenyi so few things to update here:
> > 
> > * The table of content still has the reference to the docs moved, that part should be removed
> > * Create another folder inside `/docs/user-guide` directory for advanced configuration and separate the subtopics to different .md files. I think it will be more readable that way than everything in one file.
> > * Also, `debugging.md` and `migration.md` are already in the `docs` root folder. Just move them to `docs/user-guide/advanced-configuration` folder you will create.
> > 
> > I think every other thing is perfect. Thanks for the PR
> 
> I think that we should leave the debugging and migration files in the docs root folder, for easy referencing. It's also referenced in the database config topic.

What if we update the reference in database config topic?

**Comment by LuluNwenyi** [comment]
> This section should also be in the Admin User Account Configuration md file. I guess the table of content did not capture it and I missed it in my breakdown too.



> > > @LuluNwenyi so few things to update here:
> > > 
> > > * The table of content still has the reference to the docs moved, that part should be removed
> > > * Create another folder inside `/docs/user-guide` directory for advanced configuration and separate the subtopics to different .md files. I think it will be more readable that way than everything in one file.
> > > * Also, `debugging.md` and `migration.md` are already in the `docs` root folder. Just move them to `docs/user-guide/advanced-configuration` folder you will create.
> > > 
> > > I think every other thing is perfect. Thanks for the PR
> > 
> > 
> > I think that we should leave the debugging and migration files in the docs root folder, for easy referencing. It's also referenced in the database config topic.
> 
> What if we update the reference in database config topic?

This could work

**Comment by DesmondSanctity** [comment]
@LuluNwenyi looks good now. Thanks

**Comment by LuluNwenyi** [comment]
> @LuluNwenyi looks good now. Thanks

Sure!

**Comment by samccann** [comment]
Part of https://github.com/ansible/awx-operator/issues/1360

**Comment by samccann** [comment]
Hi @LuluNwenyi ! I'm going to rebase each of your PRs one at a time to get them to the merge state. Just so know who what's happening here.

**Review by samccann — APPROVED** [review]

**Comment by samccann** [comment]
Thanks @LuluNwenyi for the docs PR! this was a sizable move for sure!

**Pull request merged**
