### PR TITLE
add GUID filter for logging

### PR DESCRIPTION
**Pull request by Zokormazo**
Signed-off-by: Julen Landa Alustiza <jlanda@redhat.com>

### CODE REVIEW

**Review by rooftopcellist — APPROVED** [review]

**Comment by shanemcd** [comment]
Can you look into why the tests are failing?

**Comment by Zokormazo** [comment]
Superseeded by #111

**Comment by Zokormazo** [comment]
> Can you look into why the tests are failing?

Looks unrelated to this PR itself. @Spredzy is working on it at #111

**Comment by shanemcd** [comment]
It now occurs to me that this is likely because the operator is using an old version of AWX. Have we released a version of AWX that uses django-guid yet?

**Comment by ryanpetrello** [comment]
> Have we released a version of AWX that uses django-guid yet?

Nope.

🔜

**Comment by Spredzy** [comment]
It was addressed in https://github.com/ansible/awx-operator/pull/76/

**Pull request closed without merging**
